/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.AttachmentController;
import Models.Attachment;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hwie
 */
public class AttachmentUI extends javax.swing.JFrame {
    
    private AttachmentController ac = null;
    JFileChooser fc = null;
       
    /**
     * Creates new form AttachmentUI
     */
    public AttachmentUI(AttachmentController ac) {
//        ac = new AttachmentController();
        this.ac = ac;
        initComponents();
    }

    private AttachmentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPhoto = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        AddFile = new javax.swing.JButton();
        AddSketch = new javax.swing.JButton();
        AddVideo = new javax.swing.JButton();
        AddLocation = new javax.swing.JButton();
        AddAudio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AddPhoto.setText("Add Photo");
        AddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPhotoActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titleLabel.setText("Attachment");

        AddFile.setText("Add File");
        AddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFileActionPerformed(evt);
            }
        });

        AddSketch.setText("Add Sketch");
        AddSketch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSketchActionPerformed(evt);
            }
        });

        AddVideo.setText("Add Video");
        AddVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVideoActionPerformed(evt);
            }
        });

        AddLocation.setText("Add Location");
        AddLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLocationActionPerformed(evt);
            }
        });

        AddAudio.setText("Add Audio");
        AddAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddSketch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(titleLabel)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSketch, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPhotoActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Photos", "jpg", "jpeg", "png");
        this.openAttachmentChooser(filter);
    }//GEN-LAST:event_AddPhotoActionPerformed

    private void AddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFileActionPerformed
        FileNameExtensionFilter filter = null;
        this.openAttachmentChooser(filter);                
    }//GEN-LAST:event_AddFileActionPerformed

    private void AddVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVideoActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Videos", "mp4", "mpeg", "wav");
        this.openAttachmentChooser(filter);
    }//GEN-LAST:event_AddVideoActionPerformed

    private void AddAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAudioActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Audios", "mp3", "mp2");
        this.openAttachmentChooser(filter);
    }//GEN-LAST:event_AddAudioActionPerformed

    private void AddSketchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSketchActionPerformed
        FileNameExtensionFilter filter = null;
        this.openAttachmentChooser(filter);
    }//GEN-LAST:event_AddSketchActionPerformed

    private void AddLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddLocationActionPerformed
    
    private void openAttachmentChooser(FileNameExtensionFilter filter) {
        System.out.println(this.ac.test);
        System.out.println(this.ac.nfeUI.getNoteId());
        JDialog dialog = new JDialog();
        final JFileChooser fc = new JFileChooser();                  
        if (filter != null) {
            
        }
        fc.setFileFilter(filter);
                
        int ret = fc.showOpenDialog(dialog);
        this.selectFile(ret, fc);
    }
    
        public void selectFile(int ret, JFileChooser fc) {
        String fileName = "", filePath = "";
        
        
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            fileName = file.getName();
            filePath = file.getAbsolutePath();
//            System.out.println(fileName);
//            System.out.println(filePath);
//            System.out.println("Clicked on attachment!");   
//            System.out.println(this.getFileExtension(file));
               
            Attachment a = new Attachment(fileName, filePath, this.getFileExtension(file));
            System.out.println(a);
            this.ac.setAttachment(a);
//                    System.out.println(this.ac.nfeUI.getNoteId());

        }  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttachmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttachmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttachmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttachmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttachmentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAudio;
    private javax.swing.JButton AddFile;
    private javax.swing.JButton AddLocation;
    private javax.swing.JButton AddPhoto;
    private javax.swing.JButton AddSketch;
    private javax.swing.JButton AddVideo;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private String getFileExtension(File file) {
        String fileName = file.getName();
        if(fileName.lastIndexOf(".") != -1 && fileName.lastIndexOf(".") != 0)
        return fileName.substring(fileName.lastIndexOf(".")+1);
        else return "";
    }
}
